[variables]
NODE_ENV = "production"

[phases.setup]
nixpkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@9.6.0 --activate",
    "pnpm install --frozen-lockfile --filter @imput/cobalt-web...",
]

[phases.build]
cmds = ["pnpm --filter @imput/cobalt-web build"]

[start]
cmd = "pnpm --filter @imput/cobalt-web preview --host 0.0.0.0 --port 3000"
