[variables]
NODE_ENV = "production"

[phases.setup]
nixpkgs = ["pnpm"]

[phases.build]
cmds = ["pnpm install --frozen-lockfile", "pnpm run build"]

[phases.install]
cmds = []

[start]
cmd = "pnpm preview --host 0.0.0.0"
